# Generated by Django 3.2 on 2022-09-20 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physicalPerson', models.BooleanField(default=False)),
                ('legalEntity', models.BooleanField(default=False)),
                ('flf', models.CharField(max_length=150, verbose_name='Name')),
                ('phoneNumber', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+998991234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('money', models.FloatField(default=0)),
                ('companyName', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='legalEntity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='physicalPerson',
            field=models.BooleanField(default=False),
        ),
    ]
